theme: minima
title: Klaatu barada nikto
author: Erik Skoog
email: eskoog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    The search for the Necronomicon continues

# social links
github_username:  eskoog # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
